about/urls.py
from django.conf.urls import url
from .views import DisplayAboutView


urlpatterns = [
    url(r'^$', DisplayAboutView.as_view(), name="about-us")
]

contacts/urls.py
from django.conf.urls import url
from .views import ContactView


urlpatterns = [
    url(r'^$', ContactView.as_view(), name="contact-us")
]

posyhubcomng/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import index
from django.contrib.sitemaps.views import sitemap

from zinnia.sitemaps import AuthorSitemap #NOQA
from zinnia.sitemaps import CategorySitemap #NOQA
from zinnia.sitemaps import EntrySitemap #NOQA
from zinnia.sitemaps import TagSitemap #NOQA

from about.sitemaps import AboutSitemap
from contacts.sitemaps import ContactSitemap
from services.sitemaps import ServiceSitemap

sitemaps = {

    'tags': TagSitemap,
    'blog': EntrySitemap,
    'authors': AuthorSitemap,
    'categories': CategorySitemap,
    'about': AboutSitemap,
    'contacts': ContactSitemap,
    'services': ServiceSitemap
}

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^contact-us/', include('contacts.urls', namespace="contact")),
    url(r'^about/', include('about.urls', namespace="about")),
    url(r'^services/', include('services.urls', namespace="services")),
    url(r'^blog/', include('zinnia.urls', namespace="blog")),
    url(r'^blog/comments/', include('fluent_comments.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^sitemap\.xml$', index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.html$', include('zinnia.urls.sitemap')),
    url(r'^$', TemplateView.as_view(template_name="posyhub/index.html"), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

services/urls.py
from django.conf.urls import url
from services.views import ServiceDetailView, ServiceListView


urlpatterns = [
    url(r'^$', ServiceListView.as_view(), name="services_list"),
    url(r'^(?P<slug>[-\w]+)/$', ServiceDetailView.as_view(), name="service_detail"),
]

templates/posyhub/_banner.html
<!--/banner-->
<div class="banner-inner">
</div>

templates/posyhub/_blog_list.html
{% load thumbnail i18n %}
<article class="blog-x {% cycle '' 'br-mar' %} row">
    {% if counter == 1 %}
      {% if post.image %}
        <div class="col-md-6 blog-img {% cycle '' 'img1' %}">
            <a href="{{ post.get_absolute_url }}" rel="post image" title="{{ post.title }}" itemprop="image">
                {% thumbnail post.image "380x400" crop="center" as im %}
                    <img src="{{ im.url }}" alt="{{ post.image_caption|default:post.title }}" class="img-responsive" />
                {% endthumbnail %}
            </a>
        </div>
      {% endif %}
        <div class="col-md-6 blog_info">
            <h5>
                <a href="{{ post.get_absolute_url }}" rel="post title" title="{{ post.title }}" itemprop="url">{{ post.title }}</a>
            </h5>
            <p>By
                {% for author in post.authors.all %}
                    <a href="{{ author.get_absolute_url }}" class="user-blog" rel="author" 
                        title="{% blocktrans %}Show all {{ author }}'s entries{% endblocktrans %}" 
                        itemprop="url">
                        {{ author }}{% if not forloop.last %}, {% endif %}
                    </a>
                {% endfor %}
            </p>
    
            {% if post.lead %}
                {{ post.lead|truncatewords_html:"20"|safe }}
            {% else %}
                {{ post.content|truncatewords_html:"20"|safe }}
            {% endif %}
            <!-- <ul class="blog_list_agile_w3ls">
                <li>
                    <a href="#">
                        <span class="fa fa-comment" aria-hidden="true"></span>
                        173</a>
                    <i>|</i>
                </li>
                <li>
                    <a href="#">
                        <span class="fa fa-heart" aria-hidden="true"></span>
                        10</a>
                    <i>|</i>
                </li>
                <li>
                    <a href="#">
                        <span class="fa fa-tag" aria-hidden="true"></span>
                        5</a>
                </li>
            </ul> -->
            <h4>{{ post.publication_date|date:"F d,Y" }}</h4>
        </div>
    {% endif %}
    
    {% if counter == 2 %}
      <div class="col-md-6 blog_info">
        <h5>
            <a href="{{ post.get_absolute_url }}" rel="post title" title="{{ post.title }}" itemprop="url">{{ post.title }}</a>
        </h5>

        <p>By
            {% for author in post.authors.all %}
              <a href="{{ author.get_absolute_url }}" class="user-blog" rel="author" 
                 title="{% blocktrans %}Show all {{ author }}'s entries{% endblocktrans %}" 
                 itemprop="url">
                 {{ author }}{% if not forloop.last %}, {% endif %}
              </a>
            {% endfor %}
        </p>

        {% if post.lead %}
          {{ post.lead|truncatewords_html:"20"|safe }}
        {% else %}
          {{ post.content|truncatewords_html:"20"|safe }}
        {% endif %}
        <!-- <ul class="blog_list_agile_w3ls">
            <li>
                <a href="#">
                    <span class="fa fa-comment" aria-hidden="true"></span>
                    173</a>
                <i>|</i>
            </li>
            <li>
                <a href="#">
                    <span class="fa fa-heart" aria-hidden="true"></span>
                    10</a>
                <i>|</i>
            </li>
            <li>
                <a href="#">
                    <span class="fa fa-tag" aria-hidden="true"></span>
                    5</a>
            </li>
        </ul> -->
        <h4>{{ post.publication_date|date:"F d,Y" }}</h4>
    </div>
    {% if post.image %}
        <div class="col-md-6 blog-img {% cycle '' 'img1' %}">
            <a href="{{ post.get_absolute_url }}" title="{{ post.title }}" rel="post image" itemprop="image">
                {% thumbnail post.image  "380x400" crop="center" as im %}
                    <img src="{{ im.url }}" alt="{{ post.image_caption|default:post.title }}" class="img-responsive" />
                {% endthumbnail %}
            </a>
        </div>
      {% endif %}
    {% endif %}
    

</article>

templates/posyhub/_blog_list2.html
{% load thumbnail i18n %}
<div class="col-lg-4 blog-side blog-top-right {% cycle '' 'two' %}"  data-aos="zoom-in">
    <article class="blog-top-right">
      {% if post.image %}
        <div class="blog-img">
          <a href="{{ post.get_absolute_url }}" title="{{ post.title }}" rel="post image" itemprop="image">
            {% thumbnail post.image "380x400" crop="center" as im %}
              <img src="{{ im.url }}" alt="{{ post.image_caption|default:post.title }}" class="img-responsive" />
            {% endthumbnail %}
          </a>
        </div>
      {% endif %}
      
      <div class="blog_info  blog-right">
        <h5>
            <a href="{{ post.get_absolute_url }}" rel="post title" title="{{ post.title }}" itemprop="url">{{ post.title }}</a>
        </h5>
        <p>By
            {% for author in post.authors.all %}
              <a href="{{ author.get_absolute_url }}" class="user-blog" rel="author" 
                title="{% blocktrans %}Show all {{ author }}'s entries{% endblocktrans %}" 
                itemprop="url">
                {{ author }}{% if not forloop.last %}, {% endif %}
              </a>
            {% endfor %}
        </p>
        {% if post.lead %}
          {{ post.lead|truncatewords_html:"20"|safe }}
        {% else %}
          {{ post.content|truncatewords_html:"20"|safe }}
        {% endif %}
        
        <ul class="blog_list_agile_w3ls">
          <li>
            <a href="#">
              <span class="fa fa-comment" aria-hidden="true"></span>
              173</a>
            <i>|</i>
          </li>
          <li>
            <a href="#">
              <span class="fa fa-heart" aria-hidden="true"></span>
              10</a>
            <i>|</i>
          </li>
          <li>
            <a href="#">
              <span class="fa fa-tag" aria-hidden="true"></span>
              5</a>
          </li>
        </ul>
        <h4>{{ post.publication_date|date:"F d,Y" }}</h4>
      </div>

    </article>
  </div>

templates/posyhub/_breadcrumbs.html
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="index.html">Home</a>
  </li>
  <li class="breadcrumb-item active">About</li>
</ol>

templates/posyhub/_copyright.html
{% load addendum_tags %}
  <div class="container">
    <div class="copyrighttop" data-aos="fade-left">
      <ul>
        <li>
          <h4>Follow us on:</h4>
        </li>
        {% if config.Facebook %}
        <li>
          <a class="facebook" href="{{ config.Facebook }}" title="Like posyhub on facebook">
            <i class="fab fa-facebook-f"></i>
          </a>
        </li>
        {% endif %}
        {% if config.Twitter %}
        <li>
          <a class="facebook" href="{{ config.Twitter }}" title="follow posyhub on twitter">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        {% endif %}
        {% if config.Google_plus %}
        <li>
          <a class="facebook" href="{{ config.Google_plus }}" title="visit our google page">
            <i class="fab fa-google-plus-g"></i>
          </a>
        </li>
        {% endif %}
        {% if config.LinkedIn %}
        <li>
          <a class="facebook" href="{{ config.LinkedIn }}" title="Visit our linkedin page">
            <i class="fab fa-linkedin"></i>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
    <div class="copyrightbottom" data-aos="fade-right">
      <p>© {% snippet 'copyright' safe=True %}2018 Digital Biz. All Rights Reserved{% endsnippet %}
      </p>

    </div>
    <div class="clearfix"></div>
  </div>

templates/posyhub/_footer.html
{% load zinnia static %}
{% load about_tags services_tags contact_tags addendum_tags %}

<div class="container">
  <div class="row footer-top-w3layouts-agile">
    <div class="col-lg-4 footer-grid" data-aos="zoom-in">
      <div class="footer-title">
        <h2>About Us</h2>
      </div>
      {% get_company_description as about_company %}
      <div class="footer-text">
        {{ about_company|truncatewords_html:"20"|safe }}
      </div>
    </div>
    <div class="col-lg-4 footer-grid" data-aos="zoom-in">
      <div class="footer-title">
        <h3>Contact Us</h3>
      </div>
      {% get_company_detail as comp %}
      <div class="footer-office-hour">
        <ul>
          <li class="hd">Address :</li>
          <li>{{ comp.get_addresses.0 }}</li>

        </ul>
        <ul>
          <li class="hd">Phone:{{ comp.get_phone_numbers.0 }}</li>
          <li class="hd">Email:
            <a href="mailto:{{ comp.get_emails.0 }}" title="Email us">{{ comp.get_emails.0 }}</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="col-lg-4 footer-grid" data-aos="zoom-in">
      <div class="footer-title">
        <h3>Subscribe</h3>
      </div>
      <p>Subscribe to our newsletter for innovative ways of how to grow your business and increase sales/profit</p>
      <form id="theform" name="theform" action="https://my.sendinblue.com/users/subscribeembed/js_id/3s8y9/id/1" class="newsletter">
        <input class="email" type="email" placeholder="Your email..." required="">
        <button class="btn1">
          <i class="far fa-envelope"></i>
        </button>
      </form>
      <div class="clearfix"></div>
    </div>

  </div>

</div>

templates/posyhub/_home_banner.html
{% load addendum_tags %}
<div class="banner">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <div class="carousel-caption">
          <h3>{% snippet 'home:first_banner_text' %}Best Web design/Internet marketing Agency for your needs{% endsnippet %}</h3>

        </div>
      </div>
      <div class="carousel-item item2">
        <div class="carousel-caption">
          <h3>{% snippet 'home:second_banner_text' %}We Deliver Quality Projects.{% endsnippet %}</h3>
        </div>
      </div>
      <div class="carousel-item item3">
        <div class="carousel-caption">
          <h3>{% snippet 'home:third_banner_text' %}Best Creative Agency for your needs{% endsnippet %}</h3>

        </div>
      </div>
      <div class="carousel-item item4">
        <div class="carousel-caption">
          <h3>{% snippet 'home:fourth_banner_text' %}We Deliver Quality Projects.{% endsnippet %}</h3>

        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" title="Previous Slide">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next" title="Next Slide">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

templates/posyhub/_home_recent_entries.html
{% load thumbnail %}
{% for entry in entries %}
 <div class="col-lg-4 bottom-sub-grid text-center aos-init aos-animate" data-aos="zoom-in" itemprop="blogUpdate" itemscope itemtype="http://schema.org/BlogPosting">
  {% if entry.image %}
    {% thumbnail entry.image "300x170" as im %}
      <img src="{{ im.url }}" class="img-thumbnail" alt="{{ entry.title }}" style="margin:{{ im|margin:"300x170" }}" itemprop="image" itemscope itemtype=" http://schema.org/ImageObject">
    {% endthumbnail %}
  {% endif %}

    <h4 class="sub-tittle_w3ls" itemprop="headline" >{{ entry.title }}</h4>
    <p itemprop="articleBody">{{ entry.lead|default:entry.content|truncatewords_html:"20"|safe }}</p>
    <p>
      <a class="btn btn-secondary view" href="{{ entry.get_absolute_url }}" role="button" title="{{ entry.title }}" rel="bookmark" itemprop="url">View details</a>
    </p>
  </div>
{% endfor %}

templates/posyhub/_js.html
{% load static %}
<!-- js -->

    	<!-- js -->
			<script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
	<!-- //js -->
	<!-- simpleLightbox -->
	<script src="{% static 'about/js/simpleLightbox.js' %}"></script>
	<script>
		$('.proj_gallery_grid a').simpleLightbox();
	</script>
	<!-- //simpleLightbox -->
	<!-- flexSlider -->
	<script defer src="{% static 'about/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript">

	  $(window).load(function(){
		$('.flexslider').flexslider({
		  animation: "slide",
		  start: function(slider){
			$('body').removeClass('loading');
		  }
		});
	  });
	</script>

	<!-- //flexSlider -->
	<!-- /js files -->
	<link href="{% static 'about/css/aos.css' %}" rel='stylesheet prefetch' type="text/css" media="all" />
	<link href="{% static 'about/css/aos-animation.css' %}" rel='stylesheet prefetch' type="text/css" media="all" />
	<script src="{% static 'about/js/aos.js' %}"></script>
	<script src="{% static 'about/js/aosindex.js' %}"></script>
	<!-- //js files -->
	<!-- start-smoth-scrolling -->
	<script type="text/javascript" src="{% static 'about/js/move-top.js' %}"></script>
	<script type="text/javascript" src="{% static 'about/js/easing.js' %}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 900);
			});
		});
	</script>
	<!-- start-smoth-scrolling -->

	<script type="text/javascript">
		$(document).ready(function () {
			/*
									var defaults = {
							  			containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear'
							 		};
									*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<a href="#home" class="scroll" id="toTop" style="display: block;" title="Back to Top">
		<span id="toTopHover" style="opacity: 1;"> </span>
	</a>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <!-- //js -->

templates/posyhub/_modal.html
<!--/model-->
	<!-- Modal -->
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Introduction Video</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body video">
					<iframe src="https://player.vimeo.com/video/33531612"></iframe>

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary">Save changes</button>
				</div>
			</div>
		</div>
	</div>
	<!--//model-->

templates/posyhub/_navigation.html
{% load addendum_tags static %}
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <a class="navbar-brand" href="{% url 'home' %}" title="posyhub logo">
    <i class="fab fa-digital-ocean"></i> posyhub</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto tp-nav text-center">
      <li class="nav-item {% if active == 'home' %}active{% endif %}">
        <a class="nav-link" href="{% url 'home' %}" title="Go to homepage">Home
            {% if active == 'home' %}
              <span class="sr-only">(current)</span>
            {% endif %}
          </a>
        </li>
        <li class="nav-item {% if active == 'about' %}active{% endif %}">
          <a class="nav-link" href="{% url 'about:about-us' %}" title="Learn more about us">About

            {% if active == 'about' %}
              <span class="sr-only">(current)</span>
              {% endif %}
            </a>
          </li>
          <li class="nav-item {% if active == 'blog' %}active{% endif %}">
            <a class="nav-link" href="/blog" title="Go to blog">Blog
              {% if active == 'blog' %}
                <span class="sr-only">(current)</span>
                {% endif %}
              </a>
            </li>

      <li class="nav-item {% if active == 'services' %}active{% endif %}">
        <a class="nav-link" href="{% url 'services:services_list' %}" title="Services we render">Services
          {% if active == 'services' %}
            <span class="sr-only">(current)</span>
          {% endif %}
        </a>
      </li>
      <li class="nav-item {% if active == 'contact' %}active{% endif %}">
        <a class="nav-link" href="{% url 'contact:contact-us' %}" title="click to contact posyhub">Contact
          {% if menu == 'contact' %}
            <span class="sr-only">(current)</span>
          {% endif %}
        </a>
      </li>
    </ul>
    <form action="{% url 'zinnia:entry_search' %}" method="get" class="form-inline my-2 my-lg-0 search">
      <input class="form-control mr-sm-2" type="search" placeholder="Search here..." name="pattern" id="searchbox" required="" {% if pattern %}value="{{ pattern }}"{% endif %}>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <a title="You can use - to exclude words or phrases, &quot;double quotes&quot; for exact phrases and the AND/OR boolean operators combined with parenthesis for complex queries.">
        <img src="{% static "zinnia/theme/img/help.png" %}" alt="?" class="help" width="14" height="14" />
      </a>
    </form>

  </div>
</nav>

templates/posyhub/index.html
{% extends "__base.html" %}
{% load zinnia %}
{% load static about_tags addendum_tags services_tags %}
{% load i18n %}

{% block title %}
    {{ block.super }} - Best Web Design/Development and Internet Marketing Agency in Nigeria
{% endblock title %}

{% block banner %}
    {% include "./_home_banner.html" %}
{% endblock banner %}

{% block extra_head %}
    <meta name="keywords" content="posyhub,internet marketing,content marketing,SEO,Search Engine Optimization,web development and design, build a website,grow your business" />
    <meta name="description" content="Posyhub is a web design/development and internet marketing firm in Nigeria geared towards promoting individuals and businesses through the power of the internet" />
    <meta property="og:title" content="Posyhub - A Web Design/Development and Internet Marketing Agency in Nigeria" />
    <meta property="og:url" content="http://www.posyhub.com" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Posyhub is a web design/development and internet marketing firm in Nigeria geared towards promoting individuals and businesses through the power of the internet" />
{% endblock %}

{% block content %}
<section class="banner-bottom">
  <div class="container">

    <!-- Three columns of text below the carousel -->
    <div class="row inner-sec-w3layouts-agileinfo">

      <div class="col-lg-5 bt-bottom-info" data-aos="fade-right">
        <h5>{% snippet "home:what_we_do" %}We help our customer to build Digital World{% endsnippet %}</h5>

      </div>
      <div class="col-lg-7 bt-bottom-info" data-aos="fade-left">
        {% get_company_description as about_comp %}
        {{ about_comp|truncatewords_html:"30"|safe }}
        <a href="{% url 'about:about-us' %}" title="Get to know more about us" itemprop="about us" rel="link">Learn more</a>
      </div>
    </div>
    <h2 class="text-center">Blog</h2><br>
    <div class="row inner-sec-w3layouts-agileinfo">
      {% get_recent_entries 6 "posyhub/_home_recent_entries.html" %}
    </div>
  </div>
  <!-- /.row -->
  </div>
</section>
<!---->

<!--/services-->
<section class="services">
  <div class="container">
    <h3 class="tittle_w3ls">Services</h3>
    <div class="row inner-sec-w3layouts-agileinfo">
      {% get_services 4 as services %}
      <div class="col-lg-4 grid_info_main" data-aos="flip-left">

        {% for service in services|slice:":2" %}
          <div class="grid_info {% cycle '' 'second' %}">
          <div class="icon_info">
            <span class="icon">
              <i class="fas {% cycle 'fa-laptop' 'fa-search' %}"></i>
            </span>
            <h5>{{ service.name }}</h5>
            <p>{{ service.description|truncatewords_html:"20"|safe }}</p>
          </div>
        </div>
        {% endfor %}

      </div>
      <div class="col-lg-4 grid_info_main mid" data-aos="flip-down">
        <img src="{% static 'about/images/hello.gif' %}" class="img-responsive" alt="marketing servicex">
      </div>
      <div class="col-lg-4 grid_info_main" data-aos="flip-right">
          {% for service in services|slice:"2:" %}
          <div class="grid_info {% cycle '' 'second' %}">
          <div class="icon_info">
            <span class="icon">
              <i class="fas {% cycle 'fa-users' 'fa-bullhorn' %}"></i>
            </span>
            <h5>{{ service.name }}</h5>
            <p>{{ service.description|truncatewords_html:"20"|safe }}</p>
          </div>
        </div>
        {% endfor %}

      </div>


    </div>
  </div>
</section>
{% endblock content %}